Repository hariduspilv/haridusportaal, pull requests merged in 2021-04, with the labels that each got.

#1415 Creating environment files #Refacator
  angular-fe/angular.json
  angular-fe/ngsw-config.json
  angular-fe/package.json
  angular-fe/src/app/_assets/header/header.component.ts
  angular-fe/src/app/_core/conf.ts
  angular-fe/src/app/_services/SettingsService.ts
  angular-fe/src/app/app.component.ts
  angular-fe/src/environments/environment.prelive.ts
  angular-fe/src/environments/environment.prod.ts
  angular-fe/src/environments/environment.ts
Labels: 2.6.1

#1414 HP-714 | accordion field names changed
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/raw/studyListViewQuery.graphql
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/studyListViewQuery.json
Labels: 2.6.1

#1419 Additional changes
  angular-fe/package-lock.json
  angular-fe/package.json
  docker/root/containers.env
  docker/root/docker-compose.yaml
Labels: 2.6.2

#1428 Amp updates
  node/modules/amp/index.js
  node/modules/botCheck/index.js
Labels: 2.6.2

#1429 Adding AMP_API env variable #AMP
  docker/root/containers.env
  node/modules/amp/index.js
Labels: 2.6.2

#1430 HP-791 Adding ordering input to images component
  angular-fe/src/app/_assets/images/images.component.ts
  angular-fe/src/app/_views/detailView/detailView.template.html
Labels: 2.6.4

#1433 Removing ngsw caching mechanism
  angular-fe/angular.json
  angular-fe/ngsw-config.json
  angular-fe/package-lock.json
  angular-fe/package.json
  angular-fe/src/app/app.module.ts
Labels: 2.6.4

#1437 OLT-155 Forceful unregistering of service worker
  angular-fe/src/app/app.component.ts
Labels: 2.6.6

#1438 Adding dev-specific robots.txt
  angular-fe/angular.json
  angular-fe/src/environments/dev/robots.txt
Labels: 2.6.6

#1439 OLT-152, OLT-157 Adding helpertext translating, new translations
  angular-fe/src/app/_views/xjson/xjson.styles.scss
  angular-fe/src/app/_views/xjson/xjson.template.html
Labels: 2.6.6

#1440 OLT-155 Refactoring unregister functionality
  angular-fe/src/app/app.component.ts
Labels: 2.6.6

#1427 HP-768 | Ametialade ja ametite esiletõstetud ametiala muudatused
  angular-fe/src/app/_assets/listItem/listItem.styles.scss
  angular-fe/src/app/_assets/listItem/listItem.template.html
  angular-fe/src/app/_assets/mainProfessionsSearchResults/mainProfessionsSearchResults.component.html
  angular-fe/src/app/_assets/mainProfessionsSearchResults/mainProfessionsSearchResults.component.ts
  angular-fe/src/app/_views/mainProfessionListView/mainProfessionListView.component.ts
  angular-fe/src/app/_views/mainProfessionListView/mainProfessionListView.template.html
Labels: 2.6.6

#1421 HP-771 | Remove description show more button from professions detailView
  angular-fe/src/app/_views/detailView/detailView.component.ts
  angular-fe/src/app/_views/detailView/detailView.template.html
Labels: 2.6.6

#1442 HP 769 and 768 changes merged
  angular-fe/src/app/_assets/listItem/listItem.styles.scss
  angular-fe/src/app/_assets/listItem/listItem.template.html
  angular-fe/src/app/_assets/mainProfessionsSearchResults/mainProfessionsSearchResults.component.html
  angular-fe/src/app/_assets/mainProfessionsSearchResults/mainProfessionsSearchResults.component.ts
  angular-fe/src/app/_views/mainProfessionListView/mainProfessionListView.component.ts
  angular-fe/src/app/_views/mainProfessionListView/mainProfessionListView.styles.scss
  angular-fe/src/app/_views/mainProfessionListView/mainProfessionListView.template.html
Labels: 2.6.6

#1443 ETUN-252 Disabling add access for invalid documents
  angular-fe/src/app/_assets/sidebar/templates/sidebar.finaldocument-access.template.html
Labels: 2.6.6

#1446 Hp 734
  angular-fe/src/app/_assets/block/block.component.ts
  angular-fe/src/app/_assets/block/block.styles.scss
  angular-fe/src/app/_core/models/list-offset-parameters.ts
  angular-fe/src/app/modules/study/components/study-list-filter/study-list-filter.component.html
  angular-fe/src/app/modules/study/components/study-list-filter/study-list-filter.component.ts
  angular-fe/src/app/modules/study/components/study-list-item/study-list-item.component.scss
  angular-fe/src/app/modules/study/components/study-list-item/study-list-item.component.ts
  angular-fe/src/app/modules/study/containers/study-list/study-list.component.html
  angular-fe/src/app/modules/study/containers/study-list/study-list.component.scss
  angular-fe/src/app/modules/study/containers/study-list/study-list.component.ts
  angular-fe/src/app/modules/study/models/study-list-view-query-parameters.ts
  angular-fe/src/app/modules/study/study-utility.ts
Labels: 2.6.6

#1447 HP-714 | Highlighted study added to the query response
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/raw/studyListViewQuery.graphql
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/studyListViewQuery.json
Labels: 2.6.6

#1448 HP-732 Adding documentation and resolving list-item-inline component …
  angular-fe/src/app/modules/study/components/study-list-item-inline-elements/study-list-item-inline-elements.component.scss
  angular-fe/src/app/modules/study/containers/study-list/study-list.component.ts
  angular-fe/src/app/modules/study/models/study.ts
  angular-fe/src/app/modules/study/study-utility.ts
Labels: 2.6.6

#1449 Translation additions #OLT, #STUDIES
  drupal/config/sync/htm_custom_translations_new.translation.yml
Labels: 2.6.6

#1460 HP-714 | Study page's auto path urls
  drupal/config/sync/pathauto.pattern.uuringud_pattern_eng.yml
  drupal/config/sync/pathauto.pattern.uuringud_pattern_est.yml
Labels: 2.6.7

#1463 Updating study detail view query image derivative
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/raw/studyDetailViewQuery.graphql
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/studyDetailViewQuery.json
Labels: 2.6.7

#1453 HP-768 - esilestõstetud ametiala säilitamine otsingutulemuste vastavusel
  angular-fe/src/app/_assets/listItem/listItem.styles.scss
  angular-fe/src/app/_assets/mainProfessionsSearchResults/mainProfessionsSearchResults.component.ts
Labels: 2.6.7

#1464 HP-569 text-based map data for screenreaders
  angular-fe/src/app/_views/oskaFieldMap/oskaFieldMap.template.html
  angular-fe/src/app/_views/schoolListView/map/schoolListMap.template.html
  angular-fe/src/styles.scss
Labels: 2.6.7

#1465 Adding prelive dockerfile to angular
  angular-fe/Dockerfile.prelive
Labels: 2.6.7

#1466 Forcibly remove service worker cache
  angular-fe/src/app/app.component.ts
Labels: 2.6.7

#1469 HP-811 Adding additional checks for data existance
  angular-fe/src/app/_assets/dropdown-list/dropdown-list.component.html
Labels: 2.6.7

#1470 Hp 813
  angular-fe/src/app/_assets/listItem/listItem.styles.scss
  angular-fe/src/app/_assets/picto/helpers/picto.ts
  angular-fe/src/app/_assets/picto/picto.component.ts
  angular-fe/src/app/_assets/picto/picto.styles.scss
  angular-fe/src/app/_assets/picto/picto.template.html
  angular-fe/src/app/_views/detailView/detailView.styles.scss
  angular-fe/src/app/_views/detailView/detailView.template.html
  angular-fe/src/app/_views/mainProfessionDataView/mainProfessionDataView.template.html
  angular-fe/src/app/_views/oskaFieldDataView/oskaFieldDataView.template.html
Labels: 2.6.7
