Repository hariduspilv/haridusportaal, pull requests merged in 2021-05, with the labels that each got.

#1484 HP-729 little corrections (authors removed from Study Detail View)
  angular-fe/src/app/modules/study/containers/study-detail/study-detail.component.html
  angular-fe/src/app/modules/study/containers/study-detail/study-detail.component.ts
  angular-fe/src/app/modules/study/models/mapped-study-page.ts
  angular-fe/src/app/modules/study/study-utility.ts
Labels: 2.7.0

#1455 HP-618 - "Liigu edasi põhisisu juurde" link
  angular-fe/src/app/_assets/article-layout/article.layout.template.html
  angular-fe/src/app/_assets/base-layout/baseLayout.template.html
  angular-fe/src/app/_assets/index.ts
  angular-fe/src/app/_assets/menu/sidemenu.component.ts
  angular-fe/src/app/_assets/skip-to-content/index.ts
  angular-fe/src/app/_assets/skip-to-content/skip-to-content.component.ts
  angular-fe/src/app/_assets/skip-to-content/skip-to-content.styles.scss
  angular-fe/src/app/_assets/skip-to-content/skip-to-content.template.html
  angular-fe/src/app/_views/homePageView/blocks/homePageView.navblock.html
  angular-fe/src/app/app.component.html
Labels: 2.7.2, conflicts

#1503 Hp release 2 9 0
  angular-fe/package-lock.json
  angular-fe/package.json
  angular-fe/patches/@agm+core+3.0.0-beta.0.patch
  angular-fe/src/app/_assets/listItem/listItem.styles.scss
  angular-fe/src/app/_assets/listItem/listItem.template.html
  angular-fe/src/app/_assets/modal/modal.template.html
  angular-fe/src/app/_assets/share/share.template.html
  angular-fe/src/app/_assets/video/video.component.scss
  angular-fe/src/app/_services/ModalService.ts
  angular-fe/src/app/_views/oskaFieldMap/oskaFieldMap.template.html
Labels: 2.9.0

#1507 Hp release 2 9 2
  angular-fe/package-lock.json
  angular-fe/package.json
  drupal/config/sync/htm_custom_translations_new.translation.yml
  drupal/web/modules/contrib/menu_item_role_access/src/MenuItemRoleAccessLinkTreeManipulator.php
  drupal/web/modules/custom/htm_custom_graphql_elasticsearch/src/Plugin/GraphQL/Fields/ElasticQuery/StudyProgrammeElasticQuery2.php
  drupal/web/modules/custom/htm_custom_translations_new/translations.json
  drupal/web/patches/menu_item_role_access_2.txt
Labels: 2.9.2, Merged

#1509 Fixing picto sharp module timeout
  .dockerignore
  angular-fe/.dockerignore
  angular-fe/Dockerfile
  angular-fe/Dockerfile.prelive
  angular-fe/Dockerfile.prod
  angular-fe/package-lock.json
  angular-fe/src/assets/fonts/iconfont.eot
  angular-fe/src/assets/fonts/iconfont.svg
  angular-fe/src/assets/fonts/iconfont.ttf
  angular-fe/src/assets/fonts/iconfont.woff
  node/.npmrc
  node/README.md
  node/modules/picto/index.js
  node/package-lock.json
  node/package.json
  node/pictos/cache/sorteerija-1981620854.png
Labels: 2.9.4

#1510 Adding amp support for studies
  node/modules/amp/fields.js
  node/modules/amp/index.js
  node/modules/amp/template.mustache
Labels: 2.9.4

#1511 Testing amp static pages
  node/modules/amp/index.js
  node/modules/amp/static.json
  node/modules/botCheck/index.js
Labels: 2.9.4

#1512 OLT-155 disable sorting for xjson select fields
  angular-fe/.npmrc
  angular-fe/src/app/_views/xjson/xjson.template.html
Labels: 2.9.4

#1513 Adding additional amp static meta tags
  node/modules/amp/index.js
  node/modules/amp/static.json
Labels: 2.9.4

#1505 HP-841 | localeOrderBy pipe for ordering with estonian alphabet
  angular-fe/src/app/_assets/formItem/formItem.template.html
  angular-fe/src/app/_pipes/index.ts
  angular-fe/src/app/_pipes/localeOrderBy.ts
Labels: 2.10.0

#1508 HP-856 | remove Innove logo
  angular-fe/src/app/_views/homePageView/homePageView.service.ts
  angular-fe/src/assets/img/homepage-footer-learning-1.svg
Labels: 2.10.0

#1504 HP-618 | reset page focus on navigation for skip to content button
  angular-fe/src/app/_assets/article-layout/article.layout.styles.scss
  angular-fe/src/app/_assets/menu/sidemenu.component.ts
  angular-fe/src/app/_services/SidemenuService.ts
  angular-fe/src/app/_views/dashboardView/dashboard.component.ts
Labels: 2.9.4

#1514 Hp release 2 9 4
  .dockerignore
  angular-fe/.dockerignore
  angular-fe/.npmrc
  angular-fe/Dockerfile
  angular-fe/Dockerfile.prelive
  angular-fe/Dockerfile.prod
  angular-fe/package-lock.json
  angular-fe/package.json
  angular-fe/src/app/_views/homePageView/homePageView.service.ts
  angular-fe/src/app/_views/xjson/xjson.template.html
  angular-fe/src/assets/fonts/iconfont.eot
  angular-fe/src/assets/fonts/iconfont.svg
  angular-fe/src/assets/fonts/iconfont.ttf
  angular-fe/src/assets/fonts/iconfont.woff
  angular-fe/src/assets/img/homepage-footer-learning-1.svg
  node/.npmrc
  node/README.md
  node/modules/amp/fields.js
  node/modules/amp/index.js
  node/modules/amp/template.mustache
  node/modules/picto/index.js
  node/package-lock.json
  node/package.json
  node/pictos/cache/sorteerija-1981620854.png
Labels: 2.9.4, Merged

#1516 HP-854 Adding app preloader based on translations request
  angular-fe/src/app/_assets/loader/loader.component.ts
  angular-fe/src/app/_assets/loader/loader.template.html
  angular-fe/src/app/_modules/translate/translate.service.ts
  angular-fe/src/app/app.component.html
  angular-fe/src/app/app.component.scss
  angular-fe/src/app/app.component.ts
Labels: 2.10.0

#1517 Encoding picto urls
  node/modules/amp/index.js
Labels: 2.10.0

#1518 HP-618 | fix burger menu in safari, I guess?
  angular-fe/src/app/_assets/header/header.styles.scss
Labels: 2.10.0

#1521 Hp release 2 10 0
  angular-fe/package-lock.json
  angular-fe/package.json
  angular-fe/src/app/_assets/article-layout/article.layout.styles.scss
  angular-fe/src/app/_assets/article-layout/article.layout.template.html
  angular-fe/src/app/_assets/base-layout/baseLayout.template.html
  angular-fe/src/app/_assets/formItem/formItem.template.html
  angular-fe/src/app/_assets/header/header.styles.scss
  angular-fe/src/app/_assets/index.ts
  angular-fe/src/app/_assets/loader/loader.component.ts
  angular-fe/src/app/_assets/loader/loader.template.html
  angular-fe/src/app/_assets/menu/sidemenu.component.ts
  angular-fe/src/app/_assets/skip-to-content/index.ts
  angular-fe/src/app/_assets/skip-to-content/skip-to-content.component.ts
  angular-fe/src/app/_assets/skip-to-content/skip-to-content.styles.scss
  angular-fe/src/app/_assets/skip-to-content/skip-to-content.template.html
  angular-fe/src/app/_modules/translate/translate.service.ts
  angular-fe/src/app/_pipes/index.ts
  angular-fe/src/app/_pipes/localeOrderBy.ts
  angular-fe/src/app/_services/SidemenuService.ts
  angular-fe/src/app/_views/dashboardView/dashboard.component.ts
  angular-fe/src/app/_views/homePageView/blocks/homePageView.navblock.html
  angular-fe/src/app/app.component.html
  angular-fe/src/app/app.component.scss
  angular-fe/src/app/app.component.ts
  docker/README.md
  node/modules/amp/index.js
Labels: 2.10.0

#1522 Adding prelive robots.txt
  angular-fe/angular.json
  angular-fe/src/environments/prelive/robots.txt
Labels: 2.10.0, Merged
