Repository hariduspilv/haridusportaal, pull requests merged in 2021-01, with the labels that each got.

#1265 #HP-534 Initially selecting silt label for charts
  angular-fe/package-lock.json
  angular-fe/package.json
  angular-fe/src/app/_assets/chart/chart.component.ts
  angular-fe/stories/assets/charts/chart.data.ts
Labels: 1.54.9

#1267 #HP-591 Adding source field to charts
  angular-fe/src/app/_assets/chart/chart.component.ts
  angular-fe/src/app/_assets/chart/chart.styles.scss
  angular-fe/src/app/_assets/chart/chart.template.html
Labels: 1.54.9

#1269 #HP-560 Oska results table dynamic color input
  angular-fe/src/app/_views/oskaResultsView/oskaResultsView.component.ts
  angular-fe/src/app/_views/oskaResultsView/oskaResultsView.template.html
Labels: 1.54.9

#1271 HP-642 | add 404 handler back
  angular-fe/src/app/app.routes.ts
Labels: 1.54.11

#1274 CI documentation update #Sprint-54
  docker/README.md
Labels: 1.54.11

#1276 HP-684 | add the search button back on tablet view
  angular-fe/src/app/_assets/header/header.styles.scss
Labels: 1.54.11

#1278 Filter null value professions from faulty request #HP-688
  angular-fe/src/app/_assets/dropdown-list/dropdown-list.component.html
  angular-fe/src/app/_assets/dropdown-list/dropdown-list.component.ts
  angular-fe/src/app/_views/detailView/detailView.component.ts
Labels: 1.54.11

#1275 Etun 207 r1
  angular-fe/src/app/_assets/studies/studies.component.ts
  angular-fe/src/app/_assets/studies/studies.model.ts
  angular-fe/src/app/_assets/studies/studies.template.html
  angular-fe/src/app/_views/digitalSignView/digitalSignView.template.html
Labels: 1.54.11

#1284 Etun 207 r2
  angular-fe/src/app/_assets/studies/studies.component.ts
Labels: 1.54.11

#1286 #HP-367 Amp picto css bugfix / LATEST
  node/modules/picto/index.js
  node/pictos/cache/sorteerija--1845974659-bot.png
  node/pictos/cache/sorteerija--1845974659.png
Labels: 1.54.11

#1287 #OLT-32 Removing translation pipe from number readonly template
  angular-fe/src/app/_views/xjson/xjson.template.html
Labels: 1.54.11

#1288 Hp release 1 54 11
  angular-fe/ngsw-config.json
  angular-fe/src/app/_assets/header/header.styles.scss
  angular-fe/src/app/_assets/mainProfessionsSearchResults/mainProfessionsSearchResults.helper.ts
  angular-fe/src/app/_assets/studies/studies.component.ts
  angular-fe/src/app/_assets/studies/studies.model.ts
  angular-fe/src/app/_assets/studies/studies.template.html
  angular-fe/src/app/_views/digitalSignView/digitalSignView.template.html
  angular-fe/src/app/_views/xjson/xjson.template.html
  angular-fe/src/app/app.routes.ts
  docker/README.md
  drupal/web/modules/custom/htm_custom_ehis_connector/src/EhisConnectorService.php
  node/modules/picto/index.js
  node/pictos/cache/sorteerija--1845974659-bot.png
  node/pictos/cache/sorteerija--1845974659.png
Labels: Release-1.54.11

#1290 Hp release 1 55 0
  angular-fe/package-lock.json
  angular-fe/package.json
  drupal/web/modules/custom/htm_custom_oska/htm_custom_oska.links.action.yml
  drupal/web/modules/custom/htm_custom_oska/htm_custom_oska.links.menu.yml
  drupal/web/modules/custom/htm_custom_oska/htm_custom_oska.links.task.yml
  drupal/web/modules/custom/htm_custom_oska/htm_custom_oska.permissions.yml
  drupal/web/modules/custom/htm_custom_oska/htm_custom_oska.routing.yml
  drupal/web/modules/custom/htm_custom_oska/oska_file_entity.page.inc
  drupal/web/modules/custom/htm_custom_oska/src/Entity/OskaEntity.php
  drupal/web/modules/custom/htm_custom_oska/src/Entity/OskaFileEntity.php
  drupal/web/modules/custom/htm_custom_oska/src/Entity/OskaFileEntityInterface.php
  drupal/web/modules/custom/htm_custom_oska/src/Entity/OskaFileEntityViewsData.php
  drupal/web/modules/custom/htm_custom_oska/src/Form/OskaFileEntityDeleteForm.php
  drupal/web/modules/custom/htm_custom_oska/src/Form/OskaFileEntityForm.php
  drupal/web/modules/custom/htm_custom_oska/src/Form/OskaFileEntitySettingsForm.php
  drupal/web/modules/custom/htm_custom_oska/src/Form/OskaImportDataForm.php
  drupal/web/modules/custom/htm_custom_oska/src/OskaEntityListBuilder.php
  drupal/web/modules/custom/htm_custom_oska/src/OskaFileEntityAccessControlHandler.php
  drupal/web/modules/custom/htm_custom_oska/src/OskaFileEntityHtmlRouteProvider.php
  drupal/web/modules/custom/htm_custom_oska/src/OskaFileEntityListBuilder.php
  drupal/web/modules/custom/htm_custom_oska/src/OskaFileEntityTranslationHandler.php
  drupal/web/modules/custom/htm_custom_oska/src/Plugin/Field/FieldType/OskaDynamicGraphField.php
  drupal/web/modules/custom/htm_custom_oska/src/Plugin/Field/FieldWidget/OskaDynamicGraphWidgetType.php
  drupal/web/modules/custom/htm_custom_oska/src/ProcessOskaData.php
  drupal/web/modules/custom/htm_custom_oska/templates/oska_file_entity.twig
Labels: 1.55.0
