Repository hariduspilv/haridusportaal, pull requests merged in 2021-02, with the labels that each got.

#1296 #HP-689 learningOpportunities sidebar only for professions
  angular-fe/src/app/_assets/sidebar/helpers/sidebar.ts
Labels: 1.55.1

#1293 HP-549 (FE) | Eelvaate parandused
  angular-fe/src/app/_views/detailView/detailView.component.ts
  angular-fe/src/app/_views/detailView/detailView.template.html
Labels: 1.55.1

#1295 HP-544 (FE) | Ametiala vaatest tühjade valdkondade eemaldamine
  angular-fe/src/app/_assets/sidebar/sidebar.component.ts
Labels: 1.55.1

#1297 HP-692 + HP-693 | listItem mobiilvaadete täiendused
  angular-fe/src/app/_assets/listItem/listItem.styles.scss
  angular-fe/src/app/_assets/listItem/listItem.template.html
Labels: 1.55.1

#1304 HP-695 R1 | Change order of items in general education view (again)
  angular-fe/src/app/_assets/studies/studies.template.html
  angular-fe/src/app/_views/digitalSignView/digitalSignView.template.html
Labels: 1.55.3

#1303 HP-693 R1 | Restore the school type field
  angular-fe/src/app/_assets/listItem/listItem.template.html
Labels: 1.55.3

#1305 Drupal conf updates
  drupal/config/sync/google_map_field.settings.yml
  drupal/config/sync/htm_custom_translations_new.translation.yml
  drupal/config/sync/smtp.settings.yml
  drupal/config/sync/user.role.oska_editor.yml
  drupal/web/modules/custom/htm_custom_translations_new/translations.json
Labels: 1.55.2

#1312 HP-651 | FE homepage changes
  angular-fe/src/app/_views/homePageView/blocks/homePageView.navblock.html
  angular-fe/src/app/_views/homePageView/blocks/homePageView.study.component.ts
  angular-fe/src/app/_views/homePageView/blocks/homePageView.study.html
  angular-fe/src/app/_views/homePageView/homePageView.model.ts
  angular-fe/src/app/_views/homePageView/homePageView.service.ts
  angular-fe/src/app/_views/homePageView/homePageView.styles.scss
  angular-fe/src/app/_views/homePageView/homePageView.template.html
  angular-fe/src/app/_views/homePageView/views/homePageView.learning.template.html
  angular-fe/src/assets/img/homepage-articles-2.svg
  angular-fe/src/assets/img/homepage-articles-3.svg
  angular-fe/src/assets/img/homepage-articles-4.svg
Labels: 1.55.4

#1314 Excluding auth.html from ngsw navigation #FE 2.0
  angular-fe/ngsw-config.json
Labels: 1.55.4

#1315 Hp release 1 55 6
  angular-fe/ngsw-config.json
  angular-fe/package-lock.json
  angular-fe/package.json
  angular-fe/src/app/_assets/index.ts
  angular-fe/src/app/_assets/sidebar/helpers/sidebar.ts
  angular-fe/src/app/_assets/sidebar/models/certificate-owner.ts
  angular-fe/src/app/_assets/sidebar/models/final-document-download-sidebar.ts
  angular-fe/src/app/_assets/sidebar/sidebar.component.ts
  angular-fe/src/app/_assets/sidebar/templates/sidebar.finaldocument-history.template.html
  angular-fe/src/app/modules/certificates/certificates.utility.ts
  angular-fe/src/app/modules/certificates/containers/final-document-dashboard-detail/final-document-dashboard-detail.component.ts
  angular-fe/src/app/modules/certificates/models/interfaces/certificate-document.ts
  angular-fe/src/app/modules/certificates/models/interfaces/certificate-final-document-dashboard-sidebar.ts
Labels: 1.55.6

#1317 Professions initially without counts #HP-625
  angular-fe/src/app/_assets/listItem/listItem.component.ts
  angular-fe/src/app/_assets/listItem/listItem.template.html
  angular-fe/src/app/_assets/mainProfessionsSearchResults/mainProfessionsSearchResults.component.html
  angular-fe/src/app/_assets/mainProfessionsSearchResults/mainProfessionsSearchResults.component.ts
  angular-fe/src/app/_assets/mainProfessionsSearchResults/mainProfessionsSearchResults.helper.ts
  angular-fe/src/app/_directives/filtersDirective.ts
  angular-fe/src/app/_views/mainProfessionListView/mainProfessionListView.component.ts
  angular-fe/src/app/_views/mainProfessionListView/mainProfessionListView.template.html
Labels: 1.55.7

#1318 #HP-716 LineClamp mixin styles for inner content
  angular-fe/src/app/_views/detailView/detailView.styles.scss
Labels: 1.55.7

#1321 #HP-717 Listitem video to secure protocol
  angular-fe/src/app/_assets/listItem/listItem.template.html
Labels: 1.55.7

#1322 HP-692 | Use translation for number employed
  angular-fe/src/app/_assets/listItem/listItem.template.html
Labels: 1.55.7

#1320 HP-651 r1 | Mobile and tablet style adjustments
  angular-fe/src/app/_views/homePageView/homePageView.styles.scss
Labels: 1.55.7

#1323 #HP-690 Updating accordion links reference
  angular-fe/src/app/_views/detailView/detailView.template.html
Labels: 1.55.7

#1324 #HP-530 Oska file entity revert
  drupal/web/modules/custom/htm_custom_oska/htm_custom_oska.links.action.yml
  drupal/web/modules/custom/htm_custom_oska/htm_custom_oska.links.menu.yml
  drupal/web/modules/custom/htm_custom_oska/htm_custom_oska.links.task.yml
  drupal/web/modules/custom/htm_custom_oska/htm_custom_oska.permissions.yml
  drupal/web/modules/custom/htm_custom_oska/htm_custom_oska.routing.yml
  drupal/web/modules/custom/htm_custom_oska/oska_file_entity.page.inc
  drupal/web/modules/custom/htm_custom_oska/src/Entity/OskaFileEntity.php
  drupal/web/modules/custom/htm_custom_oska/src/Entity/OskaFileEntityInterface.php
  drupal/web/modules/custom/htm_custom_oska/src/Entity/OskaFileEntityViewsData.php
  drupal/web/modules/custom/htm_custom_oska/src/Form/OskaFileEntityDeleteForm.php
  drupal/web/modules/custom/htm_custom_oska/src/Form/OskaFileEntityForm.php
  drupal/web/modules/custom/htm_custom_oska/src/Form/OskaFileEntitySettingsForm.php
  drupal/web/modules/custom/htm_custom_oska/src/Form/OskaImportDataForm.php
  drupal/web/modules/custom/htm_custom_oska/src/OskaEntityListBuilder.php
  drupal/web/modules/custom/htm_custom_oska/src/OskaFileEntityAccessControlHandler.php
  drupal/web/modules/custom/htm_custom_oska/src/OskaFileEntityHtmlRouteProvider.php
  drupal/web/modules/custom/htm_custom_oska/src/OskaFileEntityListBuilder.php
  drupal/web/modules/custom/htm_custom_oska/src/OskaFileEntityTranslationHandler.php
  drupal/web/modules/custom/htm_custom_oska/src/Plugin/Field/FieldType/OskaDynamicGraphField.php
  drupal/web/modules/custom/htm_custom_oska/src/Plugin/Field/FieldWidget/OskaDynamicGraphWidgetType.php
  drupal/web/modules/custom/htm_custom_oska/src/ProcessOskaData.php
  drupal/web/modules/custom/htm_custom_oska/templates/oska_file_entity.twig
Labels: 1.55.7, Merged

#1325 HP-572 - improve 404 page button aria-labels
  angular-fe/src/app/_assets/notFound/notFound.template.html
Labels: 1.55.8

#1327 semantic tables, improve aria labels
  angular-fe/src/app/_views/compareView/compareView.component.ts
  angular-fe/src/app/_views/compareView/compareView.styles.scss
  angular-fe/src/app/_views/compareView/compareView.template.html
Labels: 1.55.8

#1328 HP-727 + HP-728 | menu changes
  angular-fe/src/app/_assets/menu/sidemenu-item.component.ts
  angular-fe/src/app/_assets/menu/sidemenu.component.ts
Labels: 1.55.8

#1329 HP-587 | limit sidebar links to 5, show more button
  angular-fe/src/app/_assets/sidebar/sidebar.component.ts
  angular-fe/src/app/_assets/sidebar/sidebar.styles.scss
  angular-fe/src/app/_assets/sidebar/templates/sidebar.links.template.html
Labels: 1.55.8

#1330 HP-598 | change link to display inline block
  angular-fe/src/app/_assets/links/links.styles.scss
Labels: 1.55.8

#1332 #ETUN-240 #ETUN-241 Adding document validity check to certificate download
  angular-fe/src/app/modules/certificates/certificates.utility.ts
  angular-fe/src/app/modules/certificates/containers/certificates-detail/certificates-detail.component.ts
  angular-fe/src/app/modules/certificates/containers/final-document-dashboard-detail/final-document-dashboard-detail.component.ts
Labels: 1.55.8

#1334 #HP-311 Adding sitemap and dev env conf modifications
  angular-fe/angular.json
  angular-fe/ngsw-config.json
  angular-fe/package.json
  angular-fe/src/robots-dev.txt
  angular-fe/src/sitemap.xml
  docker/develop/Dockerfile
Labels: 1.55.8

#1335 #HP-311 Updating faulty sitemap
  angular-fe/src/sitemap.xml
Labels: 1.55.8

#1336 #HP-311 Adding dev environment robots.txt to ngsw exclude
  angular-fe/angular.json
  angular-fe/ngsw-config.json
Labels: 1.55.8

#1339 #ETUN-240 Updating dashboard certificates sort
  angular-fe/src/app/modules/certificates/certificates.utility.ts
  angular-fe/src/app/modules/certificates/components/certificates/certificates.component.ts
  angular-fe/src/app/modules/certificates/models/interfaces/certificate-document.ts
  angular-fe/src/app/modules/certificates/models/interfaces/graduation-certificate.ts
Labels: 1.55.8

#1341 #HP-557 Removing empty keys from filters
  angular-fe/src/app/_directives/filtersDirective.ts
Labels: 1.55.8

#1342 Sprint 55 hp 713
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/raw/studyDetailViewQuery.graphql
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/studyDetailViewQuery.json
Labels: 1.55.8
