Repository hariduspilv/haridusportaal, pull requests merged in 2021-06, with the labels that each got.

#1486 HP-815 | Teachers homepage changes
  angular-fe/src/app/_assets/map/map.styles.scss
  angular-fe/src/app/_assets/map/map.template.html
  angular-fe/src/app/_views/homePageView/components/homepage-articles/homePageView.articles.component.ts
  angular-fe/src/app/_views/homePageView/components/homepage-articles/homePageView.articles.html
  angular-fe/src/app/_views/homePageView/components/homepage-career-development/homePageView.careerDevelopment.component.ts
  angular-fe/src/app/_views/homePageView/components/homepage-career-development/homePageView.careerDevelopment.html
  angular-fe/src/app/_views/homePageView/components/homepage-events/homePageView.events.component.ts
  angular-fe/src/app/_views/homePageView/components/homepage-events/homePageView.events.html
  angular-fe/src/app/_views/homePageView/components/homepage-footer/homePageView.footer.component.ts
  angular-fe/src/app/_views/homePageView/components/homepage-footer/homePageView.footer.html
  angular-fe/src/app/_views/homePageView/components/homepage-line/homePageView.line.component.ts
  angular-fe/src/app/_views/homePageView/components/homepage-line/homePageView.line.styles.scss
  angular-fe/src/app/_views/homePageView/components/homepage-line/homePageView.line.template.html
  angular-fe/src/app/_views/homePageView/components/homepage-navblock/homePageView.navblock.component.ts
  angular-fe/src/app/_views/homePageView/components/homepage-navblock/homePageView.navblock.html
  angular-fe/src/app/_views/homePageView/components/homepage-slides/homePageView.slides.component.ts
  angular-fe/src/app/_views/homePageView/components/homepage-slides/homePageView.slides.html
  angular-fe/src/app/_views/homePageView/components/homepage-slogan/homePageView.slogan.component.ts
  angular-fe/src/app/_views/homePageView/components/homepage-slogan/homePageView.slogan.html
  angular-fe/src/app/_views/homePageView/components/homepage-study/homePageView.study.component.ts
  angular-fe/src/app/_views/homePageView/components/homepage-study/homePageView.study.html
  angular-fe/src/app/_views/homePageView/components/homepage-topical/homePageView.topical.component.ts
  angular-fe/src/app/_views/homePageView/components/homepage-topical/homePageView.topical.html
  angular-fe/src/app/_views/homePageView/components/job-offers-map/job-offers-map.models.ts
  angular-fe/src/app/_views/homePageView/components/job-offers-map/job-offers-map.module.ts
  angular-fe/src/app/_views/homePageView/components/job-offers-map/job-offers-map.service.ts
  angular-fe/src/app/_views/homePageView/components/job-offers-map/job-offers-map/job-offers-map.component.ts
  angular-fe/src/app/_views/homePageView/components/job-offers-map/job-offers-map/job-offers-map.styles.scss
  angular-fe/src/app/_views/homePageView/components/job-offers-map/job-offers-map/job-offers-map.template.html
  angular-fe/src/app/_views/homePageView/homePageView.component.ts
  angular-fe/src/app/_views/homePageView/homePageView.model.ts
  angular-fe/src/app/_views/homePageView/homePageView.service.ts
  angular-fe/src/app/_views/homePageView/homePageView.styles.scss
  angular-fe/src/app/_views/homePageView/index.ts
  angular-fe/src/app/_views/homePageView/views/homePageView.teaching.template.html
  angular-fe/src/assets/img/cluster_blue.svg
  angular-fe/src/assets/img/homepage-teachers-1.svg
  angular-fe/src/assets/img/homepage-teachers-2.svg
  angular-fe/src/assets/img/homepage-teachers-leaf-1.svg
  angular-fe/src/assets/img/homepage-teachers-leaf-2.svg
  angular-fe/src/assets/img/marker_blue.svg
Labels: 2.11.0

#1544 Hp 815
  angular-fe/src/app/_assets/map/map.styles.scss
  angular-fe/src/app/_views/homePageView/components/job-offers-map/job-offers-map/job-offers-map.component.ts
  angular-fe/src/app/_views/homePageView/components/job-offers-map/job-offers-map/job-offers-map.template.html
Labels: 2.11.0

#1554 HP-741 | allow iframes in detail view
  angular-fe/src/app/_views/detailView/detailView.component.ts
Labels: 2.11.2

#1561 HP-887 BE decided to fix a typo
  angular-fe/src/app/modules/certificates/components/certificate-grade-sheet/certificate-grade-sheet.component.html
  angular-fe/src/app/modules/certificates/components/certificate-grade-sheet/certificate-grade-sheet.component.ts
Labels: 2.11.4

#1562 Hp release 2 11 4
  angular-fe/src/app/_views/detailView/detailView.component.ts
  drupal/config/sync/filter.format.full_html.yml
  drupal/web/modules/custom/htm_custom_admin/htm_custom_admin.module
  drupal/web/modules/custom/htm_custom_xjson_services/src/Plugin/rest/resource/xJsonFile2RestResource.php
Labels: Merged
