Repository hariduspilv/haridusportaal, pull requests merged in 2021-03, with the labels that each got.

#1344 Fixing merge issues #HP-172 VOL2
  angular-fe/src/app/_assets/index.ts
  angular-fe/src/app/modules/home-search/components/home-search/home-search.component.html
Labels: 1.55.8

#1345 Restructuring interfaces and enums #HP-172 VOL3
  angular-fe/src/app/_assets/sidebar/helpers/sidebar.ts
  angular-fe/src/app/_assets/sidebar/sidebar.component.ts
  angular-fe/src/app/_core/models/enums/file-format.enum.ts
  angular-fe/src/app/_core/models/enums/sort-direction.enum.ts
  angular-fe/src/app/_core/models/interfaces/classifier-item-text.ts
  angular-fe/src/app/_core/models/interfaces/main.ts
  angular-fe/src/app/_core/models/interfaces/sorting.ts
  angular-fe/src/app/_core/sortingUtilities.ts
  angular-fe/src/app/modules/certificates/certificates.utility.ts
Labels: 1.55.8

#1349 Sprint 55 hp 530
  angular-fe/src/app/_assets/chart/chart.component.ts
  drupal/web/modules/custom/htm_custom_oska/htm_custom_oska.links.menu.yml
  drupal/web/modules/custom/htm_custom_oska/htm_custom_oska.links.task.yml
  drupal/web/modules/custom/htm_custom_oska/htm_custom_oska.routing.yml
  drupal/web/modules/custom/htm_custom_oska/src/Form/OskaImportDataForm.php
  drupal/web/modules/custom/htm_custom_oska/src/Plugin/Field/FieldType/OskaDynamicGraphField.php
  drupal/web/modules/custom/htm_custom_oska/src/Plugin/Field/FieldWidget/OskaDynamicGraphWidgetType.php
  drupal/web/modules/custom/htm_custom_oska/src/Plugin/GraphQL/Fields/GoogleChartQuery/GoogleChartQuery.php
  drupal/web/modules/custom/htm_custom_oska/src/Plugin/GraphQL/InputTypes/GoogleChartFilterInput.php
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/googleChartData.json
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/raw/googleChartData.graphql
Labels: 1.55.9

#1350 OLT-157 | Add helpertext field to xjson schema.
  docs/xjson_definitsioonid/MTSYS_TEGEVUSLUBA.json
  docs/xjson_definitsioonid/MTSYS_TEGEVUSLUBA_LOPETAMINE_TAOTLUS.json
  docs/xjson_definitsioonid/MTSYS_TEGEVUSLUBA_MUUTMINE_TAOTLUS.json
  docs/xjson_definitsioonid/MTSYS_TEGEVUSLUBA_SULGEMINE_TAOTLUS.json
  docs/xjson_definitsioonid/MTSYS_TEGEVUSLUBA_TAOTLUS.json
  docs/xjson_definitsioonid/MTSYS_TEGEVUSNAITAJAD.json
  docs/xjson_definitsioonid/MTSYS_TEGEVUSNAITAJAD_ARUANNE.json
  docs/xjson_definitsioonid/OLT_OTSUS.json
  docs/xjson_definitsioonid/OLT_TAOTLUS.json
  docs/xjson_definitsioonid/VPT_ESITATUD_TAOTLUS.json
  docs/xjson_definitsioonid/VPT_ESITATUD_TAOTLUS_OTSUS.json
  docs/xjson_definitsioonid/VPT_TAOTLUS.json
  drupal/web/modules/custom/htm_custom_xjson_services/src/Schemas/xJson/Form/xJsonSchema.json
  drupal/web/modules/custom/htm_custom_xjson_services/src/xJsonService.php
Labels: 1.55.9

#1353 Sprint 55 hp 530
  drupal/web/modules/custom/htm_custom_oska/src/Form/OskaImportDataForm.php
  drupal/web/modules/custom/htm_custom_oska/src/Plugin/Field/FieldWidget/OskaDynamicGraphWidgetType.php
Labels: 1.55.9

#1354 OLT-156
  drupal/config/sync/htm_custom_translations_new.translation.yml
  drupal/web/modules/custom/htm_custom_xjson_services/src/Schemas/xJson/Form/messageSchema.json
  drupal/web/modules/custom/htm_custom_xjson_services/src/xJsonService.php
Labels: 1.55.9

#1356 HP-736 Refactoring share component title attribute
  angular-fe/src/app/_views/detailView/detailView.template.html
  angular-fe/stories/assets/share/instructions.md
  angular-fe/stories/assets/share/share.html
  angular-fe/stories/layouts/article/article.stories.template.html
Labels: 1.55.9

#1357 Hp 568
  angular-fe/src/app/_assets/video/video.component.html
  angular-fe/src/app/_assets/video/video.component.ts
Labels: 1.55.9

#1358 HP-172 Adding label-count to home search
  angular-fe/src/app/_views/homeSearchListView/homeSearchListView.styles.scss
  angular-fe/src/app/_views/homeSearchListView/homeSearchListView.template.html
Labels: 1.55.9

#1360 OLT-157 Adding support for body helpertext in xjson
  angular-fe/src/app/_views/xjson/xjson.template.html
Labels: 1.55.9

#1359 HP-625 | Profession counts added
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/oskaMainProfessionListView.json
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/raw/oskaMainProfessionListView.graphql
Labels: 1.55.9

#1361 HP-625 Adding type counts to main professions
  angular-fe/src/app/_assets/mainProfessionsSearchResults/mainProfessionsSearchResults.component.ts
  angular-fe/src/app/_services/ScrollRestorationService.ts
  angular-fe/src/app/_views/homeSearchListView/homeSearchListView.styles.scss
  angular-fe/src/app/_views/homeSearchListView/homeSearchListView.template.html
  angular-fe/src/app/_views/mainProfessionListView/mainProfessionListView.component.ts
  angular-fe/src/app/_views/mainProfessionListView/mainProfessionListView.template.html
Labels: 1.55.9

#1362 HP-625 Adding 0 count to filter display
  angular-fe/src/app/_views/mainProfessionListView/mainProfessionListView.template.html
Labels: 1.55.9

#1363 HP-625 Additional check for highlighted job refresh
  angular-fe/src/app/_views/mainProfessionListView/mainProfessionListView.component.ts
Labels: 1.55.9

#1347 Hp 570
  angular-fe/src/app/_assets/dropdown-list/dropdown-list.component.html
  angular-fe/src/app/_assets/dropdown-list/dropdown-list.component.scss
  angular-fe/src/app/_assets/dropdown-list/dropdown-list.component.ts
  angular-fe/src/app/_assets/formItem/formItem.component.ts
  angular-fe/src/app/_assets/formItem/formItem.template.html
  angular-fe/src/app/_views/eventsView/eventsView.component.ts
  angular-fe/src/app/_views/eventsView/eventsView.template.html
  angular-fe/src/app/_views/newsListView/newsListView.component.ts
  angular-fe/src/app/_views/newsListView/newsListView.template.html
Labels: 1.55.9

#1364 HP-570 Fixing interface mismatch
  angular-fe/src/app/_assets/formItem/formItem.component.ts
Labels: 1.55.9

#1365 HP-581 - add aria-labels, improve share component
  angular-fe/src/app/_assets/share/share.template.html
  angular-fe/src/app/_views/detailView/detailView.template.html
  angular-fe/src/app/_views/mainProfessionListView/mainProfessionListView.template.html
Labels: 1.55.9

#1369 Sprint 55 hp 756
  drupal/config/sync/core.entity_form_display.node.studypage.default.yml
  drupal/config/sync/core.entity_view_display.node.studypage.default.yml
  drupal/config/sync/core.entity_view_display.node.studypage.teaser.yml
  drupal/config/sync/field.field.node.studypage.field_highlighted_study_intro.yml
  drupal/config/sync/field.field.node.studypage.field_person.yml
  drupal/config/sync/field.field.node.studypage.field_study_topic.yml
  drupal/config/sync/field.storage.node.field_study_topic.yml
  drupal/config/sync/language.content_settings.taxonomy_term.studytopic.yml
  drupal/config/sync/taxonomy.vocabulary.studytopic.yml
Labels: 1.55.9

#1366 HP-754 | StudyTopic klassifikaator lisatud
  drupal/config/sync/language.content_settings.taxonomy_term.studytopic.yml
  drupal/config/sync/taxonomy.vocabulary.studytopic.yml
Labels: 1.55.9

#1368 HP-755 | studyDetailViewQuery päringud muudetud
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/raw/studyDetailViewQuery.graphql
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/studyDetailViewQuery.json
Labels: 1.55.9

#1374 OLT-161 Limiting OLT application view on missing data
  angular-fe/src/app/_views/xjson/xjson.component.ts
  angular-fe/src/app/_views/xjson/xjson.template.html
Labels: 1.55.9

#1377 Sprint 55 hp 758
  drupal/config/sync/core.entity_form_display.node.studypage.default.yml
  drupal/config/sync/core.entity_view_display.node.studypage.default.yml
  drupal/config/sync/core.entity_view_display.node.studypage.teaser.yml
  drupal/config/sync/field.field.node.studypage.field_custom_boolean.yml
  drupal/config/sync/field.field.node.studypage.field_highlighted_study_intro.yml
  drupal/config/sync/field.storage.node.field_custom_boolean.yml
  drupal/config/sync/field.storage.node.field_study_tag.yml
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/raw/studyDetailViewQuery.graphql
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/studyDetailViewQuery.json
Labels: 1.5.0

#1378 Sprint 55 hp 714
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/raw/studyListViewFilterQuery.graphql
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/raw/studyListViewQuery.graphql
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/studyListViewFilterQuery.json
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/studyListViewQuery.json
Labels: 1.5.0

#1379 HP-554 | xjson schema changed to allow different date-time format
  drupal/web/modules/custom/htm_custom_xjson_services/src/Schemas/xJson/Form/dateSchema.json
Labels: 1.5.0

#1380 HP-554 | 'et' removed from xjson schema regarding vpt datepicker
  drupal/web/modules/custom/htm_custom_xjson_services/src/Schemas/xJson/Form/dateSchema.json
Labels: 1.5.0

#1381 HP-554 Adding minDate and maxDate support to xjson date inputs
  angular-fe/src/app/_views/xjson/xjson-date-range-object.ts
  angular-fe/src/app/_views/xjson/xjson.component.ts
  angular-fe/src/app/_views/xjson/xjson.template.html
Labels: 1.5.0

#1382 Hp complete dockerization
  .gitignore
  angular-fe/src/app/_services/SettingsService.ts
  docker/README.md
  docker/develop/Dockerfile.angular
  docker/develop/README.md
  docker/develop/docker-compose.yaml
  docker/develop/etc/nginx/sites-enabled/haridusportaal
  docker/develop/etc/nginx/sites-enabled/haridusportaal-fe
  docker/develop/root/data/README.md
  docker/develop/root/data/stunnel/ee-x.cert
  docker/develop/root/data/stunnel/ee-x.key
  docker/develop/root/data/stunnel/stunnel.conf
  docker/develop/root/data/web/sites/default/settings.php
  docker/develop/root/docker-compose.yaml
  docker/develop/root/environment-variables/db.env
  docker/develop/root/environment-variables/drupal.env
  docker/develop/root/environment-variables/liides.env
  docker/develop/root/environment-variables/swag.env
  nginx.twn.zone.prev.conf
Labels: 1.5.0

#1385 #HP-703 More containers and documentation
  docker/develop/README.md
  docker/develop/etc/nginx/README.md
  docker/develop/etc/nginx/certs/fullchain.pem
  docker/develop/etc/nginx/certs/privkey.pem
  docker/develop/etc/nginx/sites-enabled/haridusportaal
  docker/develop/root/data/README.md
  docker/develop/root/data/javaApp/conf/application.properties
  docker/develop/root/data/varnish/default.vcl
  docker/develop/root/data/web/sites/default/settings.php
  docker/develop/root/docker-compose.yaml
  docker/develop/root/environment-variables/elasticsearch.env
  docker/develop/root/environment-variables/varnish.env
  nginx.twn.zone.prev.conf
Labels: 1.5.0

#1386 Hp release 1 5 0
  angular-fe/package-lock.json
  angular-fe/package.json
  angular-fe/src/app/_assets/article-layout/article.layout.template.html
  angular-fe/src/app/_assets/breadcrumbs/breadcrumbs.styles.scss
  angular-fe/src/app/_assets/breadcrumbs/breadcrumbs.template.html
  angular-fe/src/app/_assets/chart/chart.component.ts
  angular-fe/src/app/_assets/dropdown-list/dropdown-list.component.html
  angular-fe/src/app/_assets/dropdown-list/dropdown-list.component.scss
  angular-fe/src/app/_assets/dropdown-list/dropdown-list.component.ts
  angular-fe/src/app/_assets/feedback/feedback.styles.scss
  angular-fe/src/app/_assets/feedback/feedback.template.html
  angular-fe/src/app/_assets/formItem/formItem.component.ts
  angular-fe/src/app/_assets/formItem/formItem.template.html
  angular-fe/src/app/_assets/share/share.template.html
  angular-fe/src/app/_assets/sidebar/sidebar.styles.scss
  angular-fe/src/app/_assets/sidebar/templates/sidebar.articles.template.html
  angular-fe/src/app/_views/detailView/detailView.template.html
  angular-fe/src/app/_views/eventsView/eventsView.component.ts
  angular-fe/src/app/_views/eventsView/eventsView.template.html
  angular-fe/src/app/_views/mainProfessionListView/mainProfessionListView.template.html
  angular-fe/src/app/_views/newsListView/newsListView.component.ts
  angular-fe/src/app/_views/newsListView/newsListView.template.html
  angular-fe/src/app/_views/xjson/xjson-date-range-object.ts
  angular-fe/src/app/_views/xjson/xjson.component.ts
  angular-fe/src/app/_views/xjson/xjson.template.html
  drupal/config/sync/core.entity_form_display.node.studypage.default.yml
  drupal/config/sync/core.entity_view_display.node.studypage.default.yml
  drupal/config/sync/core.entity_view_display.node.studypage.teaser.yml
  drupal/config/sync/field.field.node.studypage.field_custom_boolean.yml
  drupal/config/sync/field.field.node.studypage.field_highlighted_study_intro.yml
  drupal/config/sync/field.field.node.studypage.field_person.yml
  drupal/config/sync/field.field.node.studypage.field_study_topic.yml
  drupal/config/sync/field.storage.node.field_custom_boolean.yml
  drupal/config/sync/field.storage.node.field_study_tag.yml
  drupal/config/sync/field.storage.node.field_study_topic.yml
  drupal/config/sync/htm_custom_translations_new.translation.yml
  drupal/config/sync/language.content_settings.taxonomy_term.studytopic.yml
  drupal/config/sync/taxonomy.vocabulary.studytopic.yml
  drupal/web/modules/custom/htm_custom_oska/htm_custom_oska.links.menu.yml
  drupal/web/modules/custom/htm_custom_oska/htm_custom_oska.links.task.yml
  drupal/web/modules/custom/htm_custom_oska/htm_custom_oska.routing.yml
  drupal/web/modules/custom/htm_custom_oska/src/Form/OskaImportDataForm.php
  drupal/web/modules/custom/htm_custom_oska/src/Plugin/Field/FieldType/OskaDynamicGraphField.php
  drupal/web/modules/custom/htm_custom_oska/src/Plugin/Field/FieldWidget/OskaDynamicGraphWidgetType.php
  drupal/web/modules/custom/htm_custom_oska/src/Plugin/GraphQL/Fields/GoogleChartQuery/GoogleChartQuery.php
  drupal/web/modules/custom/htm_custom_oska/src/Plugin/GraphQL/InputTypes/GoogleChartFilterInput.php
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/googleChartData.json
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/raw/googleChartData.graphql
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/raw/studyDetailViewQuery.graphql
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/raw/studyListViewFilterQuery.graphql
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/raw/studyListViewQuery.graphql
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/studyDetailViewQuery.json
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/studyListViewFilterQuery.json
  drupal/web/modules/custom/htm_custom_querymap_form/Maps/studyListViewQuery.json
  drupal/web/modules/custom/htm_custom_xjson_services/src/Schemas/xJson/Form/dateSchema.json
  drupal/web/modules/custom/htm_custom_xjson_services/src/Schemas/xJson/Form/messageSchema.json
  drupal/web/modules/custom/htm_custom_xjson_services/src/xJsonService.php
Labels: 1.5.0

#1387 Latest translations for release 1.5.0
  drupal/config/sync/htm_custom_translations_new.translation.yml
  drupal/web/modules/custom/htm_custom_translations_new/translations.json
Labels: 1.5.0

#1389 HP-530 | Added missing menu links for Oska main profession and map data
  drupal/web/modules/custom/htm_custom_oska/htm_custom_oska.links.menu.yml
Labels: 1.5.0

#1391 HP-703 htm-liides develop container configuration
  docker/README.md
  docker/root/containers.env
  docker/root/docker-compose.yaml
Labels: 2.6.0

#1388 HP-581
  angular-fe/src/app/_assets/formItem/formItem.template.html
  angular-fe/src/app/_views/detailView/detailView.template.html
Labels: 2.6.0

#1392 HP-703 Amp updates
  docker/README.md
  docker/root/data/varnish/503.html
  docker/root/data/varnish/default.vcl
  docker/root/docker-compose.yaml
  node/.dockerignore
  node/.gitignore
  node/README.md
  node/modules/amp/index.js
  node/package-lock.json
  node/package.json
Labels: 2.6.0

#1393 HP-703 Amp logs directory change
  docker/root/docker-compose.yaml
  node/modules/amp/index.js
Labels: 2.6.0

#1394 HP-703 logs additions
  docker/root/data/README.md
  docker/root/data/logs/amp/amp.log
  docker/root/data/logs/logrotate/nginx
  docker/root/docker-compose.yaml
Labels: 2.6.0

#1395 Hp complete dockerization
  docker/root/containers.env
  docker/root/data/varnish/503.html
  docker/root/data/varnish/default.vcl
Labels: 2.6.0

#1396 HP-703 Angular dockerfile corrections
  angular-fe/Dockerfile.prod
  angular-fe/ngsw-config.json
  angular-fe/src/app/_core/conf.ts
Labels: 2.6.0

#1397 HP-703 Removing env file duplicates and creating release documentation
  README.md
  docker/README.md
  docker/root/environment-variables/db.env
  docker/root/environment-variables/drupal.env
  docker/root/environment-variables/elasticsearch.env
  docker/root/environment-variables/liides.env
  docker/root/environment-variables/swag.env
  docker/root/environment-variables/varnish.env
Labels: 2.6.0

#1398 Hp complete dockerization
  docker/README.md
  docker/root/data/logs/logrotate/nginx
  node/modules/amp/index.js
  node/modules/import/index.js
  node/modules/picto/index.js
  node/pictos/cache/proviisor-994276523.png
Labels: 2.6.0

#1399 Hp complete dockerization
  docker/root/data/logs/logrotate/amp
  node/modules/amp/index.js
Labels: 2.6.0

#1400 HP-703 Amp additions
  node/modules/amp/index.js
Labels: 2.6.0

#1403 ETUN-242 Removing status check from previous revision document download
  angular-fe/src/app/_assets/sidebar/sidebar.component.ts
  angular-fe/src/app/_assets/sidebar/templates/sidebar.finaldocument-history.template.html
Labels: 2.6.0

#1404 ETUN-258 Adding correct id reference on acces_code type download
  angular-fe/src/app/_assets/sidebar/sidebar.component.ts
Labels: 2.6.0

#1405 ETUN-259 Fixing bug where certificate typetitle logic ignored invalid…
  angular-fe/src/app/modules/certificates/certificates.utility.ts
  angular-fe/src/app/modules/certificates/containers/final-document-dashboard-detail/final-document-dashboard-detail.component.ts
Labels: 2.6.0

#1401 HP-573 Dashboard accessibility
  angular-fe/src/app/_assets/block/block.component.ts
  angular-fe/src/app/_assets/block/block.styles.scss
  angular-fe/src/app/_assets/block/block.template.html
  angular-fe/src/app/_assets/more.block/more.block.template.html
  angular-fe/src/app/_assets/sidebar/templates/sidebar.notifications.template.html
  angular-fe/src/app/_assets/studies/studies.template.html
  angular-fe/src/app/_views/dashboardView/dashboard.template.html
  drupal/web/modules/custom/htm_custom_translations_new/translations.json
Labels: 2.6.1

#1406 OLT-156 Adding translated message_codes xjson error handler
  angular-fe/src/app/_views/xjson/xjson.component.ts
Labels: 2.6.1

#1407 Hp release 2 6 0
  angular-fe/package-lock.json
  angular-fe/package.json
  angular-fe/src/app/_assets/breadcrumbs/breadcrumbs.template.html
  angular-fe/src/app/_assets/formItem/formItem.template.html
  angular-fe/src/app/_views/detailView/detailView.template.html
  drupal/web/modules/custom/htm_custom_oska/htm_custom_oska.links.menu.yml
  drupal/web/modules/custom/htm_custom_translations_new/translations.json
Labels: Merged
